# coding: utf-8

"""
    Father Ted API

    REST API for hand-curated Father Ted Quotes  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: dave@paddez.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import father_ted_api
from father_ted_api.api.characters_api import CharactersApi  # noqa: E501
from father_ted_api.rest import ApiException


class TestCharactersApi(unittest.TestCase):
    """CharactersApi unit test stubs"""

    def setUp(self):
        self.api = father_ted_api.api.characters_api.CharactersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_characters_get(self):
        """Test case for characters_get

        List available characters.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
