# coding: utf-8

# flake8: noqa

"""
    Father Ted API

    REST API for hand-curated Father Ted Quotes  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: dave@paddez.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from father_ted_api.api.characters_api import CharactersApi
from father_ted_api.api.episodes_api import EpisodesApi
from father_ted_api.api.quotes_api import QuotesApi
from father_ted_api.api.series_api import SeriesApi

# import ApiClient
from father_ted_api.api_client import ApiClient
from father_ted_api.configuration import Configuration
# import models into sdk package
from father_ted_api.models.quote import Quote
