# coding: utf-8

"""
    Father Ted API

    REST API for hand-curated Father Ted Quotes  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: dave@paddez.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Quote(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'series': 'str',
        'episode': 'str',
        'characters': 'list[str]',
        'quote': 'str'
    }

    attribute_map = {
        'series': 'series',
        'episode': 'episode',
        'characters': 'characters',
        'quote': 'quote'
    }

    def __init__(self, series=None, episode=None, characters=None, quote=None):  # noqa: E501
        """Quote - a model defined in Swagger"""  # noqa: E501

        self._series = None
        self._episode = None
        self._characters = None
        self._quote = None
        self.discriminator = None

        self.series = series
        self.episode = episode
        self.characters = characters
        self.quote = quote

    @property
    def series(self):
        """Gets the series of this Quote.  # noqa: E501


        :return: The series of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._series

    @series.setter
    def series(self, series):
        """Sets the series of this Quote.


        :param series: The series of this Quote.  # noqa: E501
        :type: str
        """
        if series is None:
            raise ValueError("Invalid value for `series`, must not be `None`")  # noqa: E501

        self._series = series

    @property
    def episode(self):
        """Gets the episode of this Quote.  # noqa: E501


        :return: The episode of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._episode

    @episode.setter
    def episode(self, episode):
        """Sets the episode of this Quote.


        :param episode: The episode of this Quote.  # noqa: E501
        :type: str
        """
        if episode is None:
            raise ValueError("Invalid value for `episode`, must not be `None`")  # noqa: E501

        self._episode = episode

    @property
    def characters(self):
        """Gets the characters of this Quote.  # noqa: E501


        :return: The characters of this Quote.  # noqa: E501
        :rtype: list[str]
        """
        return self._characters

    @characters.setter
    def characters(self, characters):
        """Sets the characters of this Quote.


        :param characters: The characters of this Quote.  # noqa: E501
        :type: list[str]
        """
        if characters is None:
            raise ValueError("Invalid value for `characters`, must not be `None`")  # noqa: E501

        self._characters = characters

    @property
    def quote(self):
        """Gets the quote of this Quote.  # noqa: E501


        :return: The quote of this Quote.  # noqa: E501
        :rtype: str
        """
        return self._quote

    @quote.setter
    def quote(self, quote):
        """Sets the quote of this Quote.


        :param quote: The quote of this Quote.  # noqa: E501
        :type: str
        """
        if quote is None:
            raise ValueError("Invalid value for `quote`, must not be `None`")  # noqa: E501

        self._quote = quote

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Quote, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Quote):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
